name: "Acessibility declaration scan action"

description: "Détecte la présence d'une déclaration d'accessibilité"

inputs:
  url:
    description: "URL à tester"
    required: true
  output:
    description: "Path to output file. defaults to declaration-a11y.json"
    required: true
    default: "declaration-a11y.json"

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn

    - name: Get URL HTML
      uses: ./get-html
      with:
        url: ${{ inputs.url }}
        output: result.html

    - name: Detect declaration a11y
      shell: bash
      run: |
        cd ${{ github.action_path }}
        node ${{ github.action_path }}/src/index.js ${{ inputs.url }} ${{ github.workspace }}/result.html > ${{ github.workspace }}/${{ inputs.output }}
        cat ${{ github.workspace }}/${{ inputs.output }}
