name: "DashLord init action"

description: "Parse dashlord config files"

inputs:
  url:
    description: "Single url to scan or scan all urls"
    required: false
    default: ""
  tool:
    description: "Tool to run or use all tools"
    required: false
    default: ""

outputs:
  urls:
    description: List of urls to scan as plain text
    value: ${{ steps.init.outputs.urls }}
  sites:
    description: List of sites with repositories and tools to scan as json
    value: ${{ steps.init.outputs.sites }}
  config:
    description: Full dashlord.yaml config
    value: ${{ steps.init.outputs.config }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"

    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn

    - shell: bash
      id: init
      run: |
        cd ${{ github.action_path }}

        node ${{ github.action_path }}/src/index.js
