name: "Updown init action"

description: "Create missing entries in updown.io"

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn

    - shell: bash
      id: fetch
      run: |
        cd ${{ github.action_path }}
        node ${{ github.action_path }}/src/index.js
