name: "Check URL status action"

description: "Check page status from url"

inputs:
  url:
    description: "The URL to check"
    required: true
  output:
    description: "Path to output file. defaults to url_status.json"
    required: true
    default: "url_status.json"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set +e

        echo "testing URL $1"

        wget -q -S --no-check-certificate --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0 - dashlord" ${{ inputs.url }}

        if ! [ "$?" -ne 0 ];
        then
          JSON="{\"grade\": \"A\"}"
        else
          JSON="{\"grade\": \"F\"}"
        fi

        echo "$JSON" > ${{ github.workspace }}/${{ inputs.output }}
