name: "Dashlord report action"

description: "Generate a dashlord report"

inputs:
  base-path:
    description: "base-path for the next.js build. see https://nextjs.org/docs/api-reference/next.config.js/basepath"
    required: false
  output:
    description: "Path to output file. defaults to report.json"
    required: true
    default: "report.json"
  build-website:
    description: "Whether to build the Next.js website"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: "lts/*"

    - name: Generate Dashlord report
      id: report
      shell: bash
      run: |
        export DASHLORD_REPO_PATH=${{ github.workspace }}

        echo "DASHLORD_REPO_PATH: $DASHLORD_REPO_PATH"

        cd ${{ github.action_path }}

        yarn

        # this creates config.json, report.json and trends.json
        node src/index.js

        # save report in workspace for artifact
        cp www/src/report.json ${{ github.workspace }}/${{ inputs.output }}

    - name: Build Next.js website
      if: ${{ inputs.build-website == 'true' }}
      id: build
      shell: bash
      env:
        SKIP_PREFLIGHT_CHECK: "true"
      run: |
        export NEXT_PUBLIC_REPOSITORY_URL=$(echo 'https://github.com/${{ github.repository }}')
        export NEXT_PUBLIC_BASE_PATH=$([[ -n "${{ inputs.base-path }}" ]] && echo "${{ inputs.base-path }}" || echo "")

        echo "REPOSITORY_URL: $REPOSITORY_URL"
        echo "NEXT_PUBLIC_BASE_PATH: $NEXT_PUBLIC_BASE_PATH"

        cd ${{ github.action_path }}/www

        yarn

        export NODE_OPTIONS=--max-old-space-size=8192 # prevents heap out of memory ?

        CI=false yarn build

        # prevent gh-pages jekyll build
        touch out/.nojekyll

        # save the build for gh-pages publication
        mv out ${{ github.workspace }}/build
