name: "DSFR detection action"

description: "Detect official DSFR usage"

inputs:
  url:
    description: URL to read
    required: true
  output:
    description: "Path to output file. defaults to dsfr.json"
    required: true
    default: "dsfr.json"

runs:
  using: "composite"
  steps:
    - name: Get URL HTML
      uses: Quentium-Forks/dashlord-actions/get-html@main
      with:
        url: ${{ inputs.url }}
        output: dsfr-html.html

    - shell: bash
      run: |
        set +e

        # this exits 1 when no fr-header__brand or rf-header__brand
        grep -q "\(rf\|fr\)-header__brand" < ./dsfr-html.html
        if [ $? -eq 0 ]; then
          JSON="{\"detected\": true}"
        else
          JSON="{\"detected\": false}"
        fi

        echo "$JSON" > ${{ github.workspace }}/${{ inputs.output }}

        cat ${{ github.workspace }}/${{ inputs.output }}
