name: "Get URL HTML action"

description: "Get HTML content from a URL"

inputs:
  url:
    description: URL to read HTML
    required: true
  output:
    description: "Path to output file. defaults to result.html"
    required: true
    default: "result.html"
  language:
    description: Default environment LANGUAGE
    required: false
    default: fr

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        cache: "yarn"

    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn

    - shell: bash
      id: fetch
      run: |
        cd ${{ github.action_path }}
        export LANGUAGE="${{ inputs.language }}"
        node ${{ github.action_path }}/bin/index.js ${{ inputs.url }} > ${{ github.workspace }}/${{ inputs.output }}
