/// <reference path="./index.d.ts" />

type UrlReportSummary = {
  "404Count"?: number;
  "404Grade"?: string;
  apdex?: number;
  apdexGrade?: string;
  codescanCount?: number;
  codescanGrade?: string;
  cookiesCount?: number;
  cookiesGrade?: string;
  declaration_a11yGrade?: string;
  "declaration_rgpd-mlGrade"?: string;
  "declaration_rgpd-pcGrade"?: string;
  dependabotCount?: number;
  dependabotGrade?: string;
  dsfrGrade?: string;
  ecoindexGrade?: string;
  httpGrade?: string;
  lighthouse_accessibility?: number;
  lighthouse_accessibilityGrade?: string;
  "lighthouse_best-practices"?: number;
  "lighthouse_best-practicesGrade"?: string;
  lighthouse_performance?: number;
  lighthouse_performanceGrade?: string;
  lighthouse_pwa?: number;
  lighthouse_pwaGrade?: string;
  lighthouse_seo?: number;
  lighthouse_seoGrade?: string;
  nmapGrade?: string;
  nmapOpenPortsCount?: number;
  nmapOpenPortsGrade?: string;
  sonarcloudGrade?: string;
  statsCount?: number;
  statsGrade?: string;
  testsslExpireDate?: string;
  testsslExpireSoon?: boolean;
  testsslGrade?: string;
  trackersCount?: number;
  trackersGrade?: string;
  trivyCount?: number;
  trivyGrade?: string;
  uptime?: number;
  uptimeGrade?: string;
  zapCount?: number;
  zapGrade?: string;
};
