name: "RGPD declaration scan action"

description: "Détecte la présence de mentions légales et de politiques de confidentialité"

inputs:
  thirdparties:
    description: "Thirdparties action output to analyze trackers"
    required: false
    default: "{}"
  url:
    description: "URL à tester"
    required: true
  output:
    description: "Path to output file. defaults to declaration-rgpd.json"
    required: true
    default: "declaration-rgpd.json"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: "lts/*"

    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn

    - name: Get URL HTML
      uses: Quentium-Forks/dashlord-actions/get-html@main
      with:
        url: ${{ inputs.url }}
        output: result.html

    - name: Detect declaration rgpd
      shell: bash
      run: |
        cd ${{ github.action_path }}

        THIRDPARTIES=$(echo ${{ inputs.thirdparties }} | jq -c 'del(.endpoints)')
        THIRDPARTIES_STR="${THIRDPARTIES//'/\'}" # escapes single quotes
        THIRDPARTIES_STR="${THIRDPARTIES//\\"/"}" # remove escaped double quotes

        echo $THIRDPARTIES_STR

        node ${{ github.action_path }}/src/index.js ${{ inputs.url }} ${{ github.workspace }}/result.html "${THIRDPARTIES_STR}" > ${{ github.workspace }}/${{ inputs.output }}

        cat ${{ github.workspace }}/${{ inputs.output }}
