name: "Detect 404 action"

description: "Detect 404s on some URL"

inputs:
  url:
    description: URL to check
    required: true
  output:
    description: "Path to output file. defaults to 404.json"
    required: true
    default: "404.json"
  depth:
    description: wget spider depth
    required: false
    default: "10"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "lts/*"

    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn

    - shell: bash
      run: |
        cd ${{ github.action_path }}

        # ensure wget output is parsable
        export LANG=en_GB.UTF-8 

        # wget return error exit code when errors founds
        OUT=$(timeout -p -f 580 wget -e robots=off --no-check-certificate --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0 - dashlord" --level=${{ inputs.depth }} --spider --recursive 2>&1 > /dev/null ${{ inputs.url }})
        echo "$OUT" | yarn -s wget-parser > ${{ github.workspace }}/${{ inputs.output }}

        # temp fix if url has to be www
        broken=$(jq '.broken | length' ${{ github.workspace }}/${{ inputs.output }})
        links=$(jq '.links | length' ${{ github.workspace }}/${{ inputs.output }})
        if { [ "${broken}" -eq 0 ] || [ "${links}" -eq 0 ]; } && ! echo ${{ inputs.url }} | grep -q "www." ; then
          OUT=$(timeout -p -f 580 wget -e robots=off --no-check-certificate --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0 - dashlord" --level=${{ inputs.depth }} --spider --recursive 2>&1 > /dev/null $(echo ${{ inputs.url }} | sed -e 's#https://#https://www.#'))
          echo "$OUT" | yarn -s wget-parser > ${{ github.workspace }}/${{ inputs.output }}
        fi

        cat ${{ github.workspace }}/${{ inputs.output }} | jq ".links | length"
        cat ${{ github.workspace }}/${{ inputs.output }} | jq ".broken | length"
