name: "Detect 404 action"

description: "Detect 404s on some URL"

inputs:
  url:
    description: URL to check
    required: true
  output:
    description: "Path to output file. defaults to 404.json"
    required: true
    default: "404.json"
  depth:
    description: wget spider depth
    required: false
    default: "10"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        cache: "yarn"
        cache-dependency-path: "404/yarn.lock"

    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn

    - shell: bash
      run: |
        cd ${{ github.action_path }}

        # ensure wget output is parsable
        export LANG=en_GB.UTF-8 

        # wget return error exit code when errors founds
        wget --level=${{ inputs.depth }} --spider --recursive 2>&1 >/dev/null ${{ inputs.url }} | yarn -s wget-parser > ${{ inputs.output }}

        cat ${{ inputs.output }}
