name: "SonarCloud data extraction action"

description: "Extract data from sonarcloud API"

inputs:
  repos:
    description: "Comma separated list of repos to get results for"
    required: true
  output:
    description: "Path to output file. defaults to sonarcloud.json"
    required: true
    default: "sonarcloud.json"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        cache: "yarn"

    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn

    - name: Fetch data
      shell: bash
      run: |
        cd ${{ github.action_path }}
        node ${{ github.action_path }}/src/index.js ${{ inputs.repos }} > ${{ github.workspace }}/${{ inputs.output }}
