name: Tests dsfr action

on:
  push:
    branches: ["*"]
    paths:
      - dsfr/**
      - .github/workflows/dsfr.yml
  pull_request:
    branches: ["*"]
    paths:
      - dsfr/**
      - .github/workflows/dsfr.yml

jobs:
  tests-dsfr-valid:
    runs-on: ubuntu-latest
    name: Test dsfr valid
    continue-on-error: true
    strategy:
      matrix:
        item:
          - name: talents
            url: "https://talents.ssi.gouv.fr"
          - name: histologe
            url: "https://histologe.beta.gouv.fr/"
          - name: beta
            url: "https://beta.gouv.fr"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test DSFR detection on ${{ matrix.item.name }}
        uses: ./dsfr
        with:
          url: ${{ matrix.item.url }}
          output: ${{ matrix.item.name }}.json

      - shell: bash
        run: |
          grep "\"detected\": true" < ${{ matrix.item.name }}.json

  tests-dsfr-invalid:
    runs-on: ubuntu-latest
    name: Test dsfr invalid
    continue-on-error: true
    strategy:
      matrix:
        item:
          - name: anais
            url: "https://anais.beta.gouv.fr/"
          - name: mes-evenements
            url: "https://mesevenementsemploi.pole-emploi.fr/"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test DSFR detection on ${{ matrix.item.name }}
        uses: ./dsfr
        with:
          url: ${{ matrix.item.url }}
          output: ${{ matrix.item.name }}.json

      - shell: bash
        run: |
          grep "\"detected\": false" < ${{ matrix.item.name }}.json
