name: Tests ecoindex action

on:
  push:
    branches: ["*"]
    paths:
      - ecoindex/**
      - .github/workflows/ecoindex.yml
  pull_request:
    branches: ["*"]
    paths:
      - ecoindex/**
      - .github/workflows/ecoindex.yml

jobs:
  tests-ecoindex:
    runs-on: ubuntu-latest
    name: Test ecoindex
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ecoindex scanner
        uses: ./ecoindex
        with:
          url: https://maisondelautisme.gouv.fr
          output: results.json

      - shell: bash
        run: |
          python -m json.tool < results.json
          cat results.json
