name: Test get-html action

on:
  push:
    branches: ["*"]
    paths:
      - get-html/**
      - .github/workflows/get-html.yml
  pull_request:
    branches: ["*"]
    paths:
      - get-html/**
      - .github/workflows/get-html.yml

jobs:
  tests-get-html:
    runs-on: ubuntu-latest
    name: Test get-html
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - shell: bash
        run: |
          ls -la

      - uses: ./get-html
        name: test some URL
        with:
          url: https://opentermsarchive.org
          output: result.html

      - shell: bash
        run: |
          cat result.html | grep Accessibilité

      - uses: ./get-html
        name: test user-agent
        with:
          url: https://httpbin.org/user-agent
          output: user-agent.html

      - shell: bash
        run: |
          cat user-agent.html | grep dashlord
