name: Test init from txt

on:
  push:
    branches: ["*"]
    paths:
      - init-from-txt/**
      - .github/workflows/init-from-txt.yml
  pull_request:
    branches: ["*"]
    paths:
      - init-from-txt/**
      - .github/workflows/init-from-txt.yml
  workflow_dispatch:
    inputs:
      url:
        description: "Single url to scan or scan all urls"
        required: false
        default: ""

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Prepare full scan
    outputs:
      sites: ${{ steps.init.outputs.sites }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: init
        uses: ./init-from-txt
        with:
          count: 100
          txtPath: ".github/test_urls.txt"

      - shell: bash
        id: test
        run: |
          EXPECTED="[{url: https://row1.com}, {url: https://row2.com}, {url: https://row3.com}, {url: https://row4.com}, {url: https://row5.com}, {url: https://row6.com}, {url: https://row7.com}, {url: https://row8.com}, {url: https://row9.com}]"
          RESULT="${{ steps.init.outputs.sites }}"
          echo "RESULT=$RESULT"
          [[ "$EXPECTED" == "$RESULT" ]]

  scans:
    runs-on: ubuntu-latest
    name: Scan
    needs: tests
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        sites: ${{ fromJson(needs.tests.outputs.sites) }}
    steps:
      - shell: bash
        run: |
          echo "${{ matrix.sites.url }}"
