name: Tests lhci action

on:
  push:
    branches: ["*"]
    paths:
      - lhci/**
      - .github/workflows/lhci.yml
  pull_request:
    branches: ["*"]
    paths:
      - lhci/**
      - .github/workflows/lhci.yml

jobs:
  tests-lhci:
    runs-on: ubuntu-latest
    name: Test lhci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: ./lhci
        with:
          url: https://opentermsarchive.org,https://domifa.fabrique.social.gouv.fr
          language: fr

      - shell: bash
        name: test url with french redirection
        run: |
          ls .lighthouseci
          cat .lighthouseci/*.json | grep '"finalUrl": "https://opentermsarchive.org/fr/"'

      - shell: bash
        name: test second URL
        run: |
          ls .lighthouseci
          cat .lighthouseci/*.json | grep '"finalUrl": "https://domifa.fabrique.social.gouv.fr/"'
