name: Release

on:
  workflow_dispatch:
  push:
    branches: [main, alpha, beta, next]

permissions:
  id-token: write  # Required for OIDC token generation

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Get GitHub App Token
      id: token
      uses: SocialGouv/token-bureau@main
      with:
        token-bureau-url: https://token-bureau.fabrique.social.gouv.fr
        audience: socialgouv

    - uses: SocialGouv/actions/autodevops-release@v1
      with:
        github-token: ${{ steps.token.outputs.token }}
        author-name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
        author-email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
      
    - name: Create tag v1
      env:
        GITHUB_TOKEN: "${{ steps.token.outputs.token }}"
      run: |
        git config user.name "${{ secrets.SOCIALGROOVYBOT_NAME }}"
        git config user.email "${{ secrets.SOCIALGROOVYBOT_EMAIL }}"
        git tag -d v1
        git tag v1
        git push origin v1
