name: Tests sonarcloud action

on:
  push:
    branches: ["*"]
    paths:
      - sonarcloud/**
      - .github/workflows/sonarcloud.yml
  pull_request:
    branches: ["*"]
    paths:
      - sonarcloud/**
      - .github/workflows/sonarcloud.yml

jobs:
  tests-sonarcloud:
    runs-on: ubuntu-latest
    name: Test sonarcloud
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: "${{ github.action_path }}/yarn.lock"

      - name: Run JS tests
        shell: bash
        run: |
          cd sonarcloud
          yarn
          yarn test

      - name: Run action
        uses: ./sonarcloud
        with:
          repos: sensgithub/eHospital,zabbix/zabbix
          output: sonar-output.json

      - name: Test action results
        shell: bash
        run: |
          cat sonar-output.json
          [[ $(cat sonar-output.json | jq -r '. | length') -eq "2" ]] || (echo "Error: Should get 2 results" && exit 1)
          cat sonar-output.json | jq -e '.[0].result.status.vulnerabilities' 
          cat sonar-output.json | jq -e '.[1].result.status.vulnerabilities'
